# 開発用コンテナ
version: "3.8"
services:
  my_favorite_python_env:
    build:
      image: arrowkato/my_favorite_python_env:latest
    container_name: my_favorite_python_env
    restart: "no"
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    stdin_open: true
