name: build_docker_image

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build_docker_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: "actions/checkout@v3"
      - name: login to Docker Hub
        uses: "docker/login-action@v2"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


