name: apply linters

on:
  push:
    paths:
      - "**/*.py"
      - ".github/workflows/lint.yml"

jobs:
  apply_linters:
    runs-on: ubuntu-22.04
    container:
      image: arrowkato/my_favorite_python_env:latest
      volumes:
        - $GITHUB_WORKSPACE:/app
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: poetry install
        run: . ~/.bash_profile && poetry install --no-root
      - name: run flake8
        run: . ~/.bash_profile && poetry run flake8 $(git ls-files "*.py")
      - name: run mypy
        run: . ~/.bash_profile && poetry run mypy .
      - name: run black
        run: . ~/.bash_profile && poetry run black $(git ls-files "*.py") --check
      - name: run isort
        run: . ~/.bash_profile && poetry run isort $(git ls-files "*.py") --check
